### ISSUE TITLE
.aasx cannot be opened when Referable observed of BasicEventElement has no Type

### ISSUE THREAD

**Issue by jannisjung** [eclipse-aaspe/aaspe#16]
**Describe the bug**
AASXPackageExplorer cannot open an aasx-file contains a BasicEvent that has no observable defined (and therefore it's type attribute is missing)

**To Reproduce**
* Used AASPE version:aasx-package-explorer.2023-11-17.alpha]
* Create and save an AAS with a submodel and a submodElement of type BasicEventElement, provide a idShort for the BasicEventElement ane leave the rest as is.
* Save the file
* Try loading the resulting .aasx file
* Or load the provided file (that was created within the given version of the AASPE.)
[TestAASBasicEvent.zip](https://github.com/eclipse-aaspe/aaspe/files/14128317/TestAASBasicEvent.zip) (File ending has to be changed from .zip to .aasx)

**Expected behavior**
The aasx file loads in AASPE

**Screenshots**
![Screenshot 2024-02-01 175716](https://github.com/eclipse-aaspe/aaspe/assets/92165516/d3e8880f-2d48-41cd-86de-5e3bed544bad)

**Additional Information**
the attribute "observed" is a Referable which does not necessarily need a idShort: NameType nor a category: NameType [0..1]

**Comment by juileetikekar** [comment]
Hi @jannisjung,

Thank you for raising the issue!!

I had a look into attached "TestAASBasicEvent.aasx" file and tried to reproduce the issue as well. In both the cases, the attribute "observed" is not being modelled. However, as per the specifications, the attribute "observed" is a mandatory attribute for "BasicEventElement" (screenshot 1 in the end). Thus, while loading the file in AASPE, an exception is thrown, as it cannot find a mandatory parameter "observed". 

Comment on "Additional information" : The attribute "observed" is not a referable, but it is a **reference** to the referable. The exception here is thrown because of missing "observed", and not because of IdShort.

Screenshot 1:
![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/9ccc6b87-999d-4e90-828d-e09b6cce2640)

**Comment by jannisjung** [comment]
Hi @juileetikekar , thank you for bringing this to my notice. In this case, I have to point out that the above attached .aasx file was created with AASPE and could be saved without an error message or warning. Only the subsequent opening failed. This means that AASPE does not check whether the mandatory observed attribute has been defined when the BasicEventElement was created.

**Comment by juileetikekar** [comment]
Hi @jannisjung,

Current implementation does not check for mandatory attributes.
